### ISSUE TITLE
Running interactively with PyPy no longer works

### ISSUE THREAD

**Issue by thomasmulvaney** [pixie-lang/pixie#304]
This used to be great because it was so much faster than regular python, but doesn't seem to work anymore for me due to stacklets. Is there a work around?

**Comment by thomasmulvaney** [comment]
Ok it seems you need a recent version which supports STM such as pypy 2.5.1. You can download prebuilt binaries here http://pypy.org/download.html

Perhaps fetching the prebuilt binary could be part of fetch externals, as it really makes hacking faster and more fun.

**Comment by andrewchambers** [comment]
you should just build your own pypy and install it...

**Comment by thomasmulvaney** [comment]
@andrewchambers I've closed this as it seems that even the newer STM branch can't run pixie interactively. I get the following error when I set the PYTHON var in the Makefile to pypy I get the following error:

```
make run_interactive
[forking: for now, this operation can take some time]
[forking: for now, this operation can take some time]
[forking: for now, this operation can take some time]
[forking: for now, this operation can take some time]
[forking: for now, this operation can take some time]
[forking: for now, this operation can take some time]
[forking: for now, this operation can take some time]
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-default-38/platcheck_1.c -o /tmp/usession-default-38/platcheck_1.o
[forking: for now, this operation can take some time]
[platform:execute] gcc /tmp/usession-default-38/platcheck_1.o -pthread -Wl,--export-dynamic -lintl -lrt -o /tmp/usession-default-38/platcheck_1
[forking: for now, this operation can take some time]
[forking: for now, this operation can take some time]
[forking: for now, this operation can take some time]
[forking: for now, this operation can take some time]
[forking: for now, this operation can take some time]
[pypy]
Traceback (most recent call last):
  File "<builtin>/app_main.py", line 75, in run_toplevel
  File "target.py", line 322, in <module>
    entry_point(sys.argv)
  File "target.py", line 154, in entry_point
    pixie.vm.stacklet.init()
  File "/home/tom/code/pixie/pixie/vm/stacklet.py", line 18, in init
    global_state._th = rstacklet.StackletThread(rt.__config__)
  File "/home/tom/code/pixie/externals/pypy/rpython/rlib/rstacklet.py", line 14, in __init__
    self._gcrootfinder = _getgcrootfinder(config, we_are_translated())
  File "/home/tom/code/pixie/externals/pypy/rpython/rlib/rstacklet.py", line 76, in _getgcrootfinder
    py.test.skip("cannot run the stacklet tests on top of pypy: "
  File "/home/tom/code/pixie/externals/pypy/_pytest/runner.py", line 447, in skip
    raise Skipped(msg=msg)
Skipped: cannot run the stacklet tests on top of pypy: calling directly the C function stacklet_switch() will crash, depending on details of your config
Makefile:63: recipe for target 'run_interactive' failed
make: *** [run_interactive] Error 1
```
It seems that the stacklet stuff is not compatible with pypy.

**Comment by andrewchambers** [comment]
thats pretty lame.
