### ISSUE TITLE
Building on OS X -- stacklet.h?

### ISSUE THREAD

**Issue by prologic** [pixie-lang/pixie#457]
Is there some voodoo magic required to get pixie even working interactively?

I'm getting a "file not found" error for ```src/stacklet/stacklet.h``

Full log:

```#!bash
(pixie)
prologic@nbowers-mbp
Wed Dec 02 19:20:06
~/tmp/pixie
 (master) 0 0
$ PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.0.13/lib/pkgconfig make run_interactive
[version:WARNING] Errors getting Mercurial information: Not running from a Mercurial repository!
[platform:execute] clang -c -arch x86_64 -O3 -fomit-frame-pointer -mmacosx-version-min=10.5 -mdynamic-no-pic /var/folders/t7/gp30573d0ls9l67qb4yvnjd18xyrc0/T/usession-unknown-97/platcheck_1.c -o /var/folders/t7/gp30573d0ls9l67qb4yvnjd18xyrc0/T/usession-unknown-97/platcheck_1.o
[platform:execute] clang -c -arch x86_64 -O3 -fomit-frame-pointer -mmacosx-version-min=10.5 -mdynamic-no-pic /var/folders/t7/gp30573d0ls9l67qb4yvnjd18xyrc0/T/usession-unknown-97/platcheck_2.c -o /var/folders/t7/gp30573d0ls9l67qb4yvnjd18xyrc0/T/usession-unknown-97/platcheck_2.o
[platform:execute] clang -c -arch x86_64 -O3 -fomit-frame-pointer -mmacosx-version-min=10.5 -mdynamic-no-pic /var/folders/t7/gp30573d0ls9l67qb4yvnjd18xyrc0/T/usession-unknown-97/platcheck_4.c -o /var/folders/t7/gp30573d0ls9l67qb4yvnjd18xyrc0/T/usession-unknown-97/platcheck_4.o
[platform:execute] clang -c -arch x86_64 -O3 -fomit-frame-pointer -mmacosx-version-min=10.5 -mdynamic-no-pic /var/folders/t7/gp30573d0ls9l67qb4yvnjd18xyrc0/T/usession-unknown-97/platcheck_8.c -o /var/folders/t7/gp30573d0ls9l67qb4yvnjd18xyrc0/T/usession-unknown-97/platcheck_8.o
[platform:WARNING] /var/folders/t7/gp30573d0ls9l67qb4yvnjd18xyrc0/T/usession-unknown-97/platcheck_8.c:92:1: warning: implicit declaration of function 'mremap' is invalid in C99 [-Wimplicit-function-declaration]
[platform:WARNING] mremap(NULL, 0, 0, 0);
[platform:WARNING] ^
[platform:WARNING] 1 warning generated.
[platform:execute] clang /var/folders/t7/gp30573d0ls9l67qb4yvnjd18xyrc0/T/usession-unknown-97/platcheck_8.o -arch x86_64 -mmacosx-version-min=10.5 -o /var/folders/t7/gp30573d0ls9l67qb4yvnjd18xyrc0/T/usession-unknown-97/platcheck_8
[platform:execute] clang -c -arch x86_64 -O3 -fomit-frame-pointer -mmacosx-version-min=10.5 -mdynamic-no-pic -I/Users/prologic/.virtualenvs/pixie/lib/python2.7/site-packages/rpython/translator/c /var/folders/t7/gp30573d0ls9l67qb4yvnjd18xyrc0/T/usession-unknown-97/platcheck_14.c -o /var/folders/t7/gp30573d0ls9l67qb4yvnjd18xyrc0/T/usession-unknown-97/platcheck_14.o
Traceback (most recent call last):
  File "target.py", line 311, in <module>
    rt.init()
  File "/Users/prologic/tmp/pixie/pixie/vm/rt.py", line 74, in init
    import pixie.vm.stacklet
  File "/Users/prologic/tmp/pixie/pixie/vm/stacklet.py", line 1, in <module>
    import rpython.rlib.rstacklet as rstacklet
  File "/Users/prologic/.virtualenvs/pixie/lib/python2.7/site-packages/rpython/rlib/rstacklet.py", line 2, in <module>
    from rpython.rlib import _rffi_stacklet as _c
  File "/Users/prologic/.virtualenvs/pixie/lib/python2.7/site-packages/rpython/rlib/_rffi_stacklet.py", line 23, in <module>
    rffi_platform.verify_eci(eci.convert_sources_to_files())
  File "/Users/prologic/.virtualenvs/pixie/lib/python2.7/site-packages/rpython/rtyper/tool/rffi_platform.py", line 90, in verify_eci
    configure(CConfig)
  File "/Users/prologic/.virtualenvs/pixie/lib/python2.7/site-packages/rpython/rtyper/tool/rffi_platform.py", line 247, in configure
    res[key] = value.question(writer.ask_gcc)
  File "/Users/prologic/.virtualenvs/pixie/lib/python2.7/site-packages/rpython/rtyper/tool/rffi_platform.py", line 552, in question
    ask_gcc("")
  File "/Users/prologic/.virtualenvs/pixie/lib/python2.7/site-packages/rpython/rtyper/tool/rffi_platform.py", line 194, in ask_gcc
    try_compile_cache([self.path], eci)
  File "/Users/prologic/.virtualenvs/pixie/lib/python2.7/site-packages/rpython/tool/gcc_cache.py", line 68, in try_compile_cache
    platform.compile(c_files, eci)
  File "/Users/prologic/.virtualenvs/pixie/lib/python2.7/site-packages/rpython/translator/platform/__init__.py", line 53, in compile
    ofiles = self._compile_o_files(cfiles, eci, standalone)
  File "/Users/prologic/.virtualenvs/pixie/lib/python2.7/site-packages/rpython/translator/platform/__init__.py", line 75, in _compile_o_files
    ofiles.append(self._compile_c_file(self.cc, cfile, compile_args))
  File "/Users/prologic/.virtualenvs/pixie/lib/python2.7/site-packages/rpython/translator/platform/posix.py", line 40, in _compile_c_file
    cwd=str(cfile.dirpath()))
  File "/Users/prologic/.virtualenvs/pixie/lib/python2.7/site-packages/rpython/translator/platform/__init__.py", line 139, in _execute_c_compiler
    self._handle_error(returncode, stdout, stderr, outname)
  File "/Users/prologic/.virtualenvs/pixie/lib/python2.7/site-packages/rpython/translator/platform/__init__.py", line 151, in _handle_error
    raise CompilationError(stdout, stderr)
rpython.translator.platform.CompilationError: CompilationError(err="""
	/var/folders/t7/gp30573d0ls9l67qb4yvnjd18xyrc0/T/usession-unknown-97/platcheck_14.c:79:10: fatal error: 'src/stacklet/stacklet.h' file not found
	#include <src/stacklet/stacklet.h>
	         ^
	1 error generated.
	""")
make: *** [run_interactive] Error 1
```

I obviously do have Xcode Command line Tools installed as well as well as Homebrew. What am I missing here?

**Comment by heyLu** [comment]
This sounds like something is wrong with `pypy`.  Can you remove the `externals` directory and try building again?

**Comment by mpenet** [comment]
make clean could be a good idea too (i think it deletes externals as well).

**Comment by prologic** [comment]
This isn't apypy I'm building with; but [rpython](https://pypi.python.org/pypi/rpython)

If building pixie doesn't work with the published and separate RPython toolchain above then is this something I should try to fix/resolve with the PyPy team? Perhaps something is missing from the package/tool or broken in some strange ways (*hence the errors*).

**Comment by heyLu** [comment]
It's rpython, yes, but we pull in pypy which contains rpython.  It sounds as if that step went wrong, so please run `make clean` first, followed by either `make run_interactive` or `make build_with_jit`, which builds the `pixie-vm` binary.

**Comment by prologic** [comment]
In that case I *think* what I did wrong was:

```#!bash
mkvirtualenv pixie
pip install rpython
make
```

So if I remove the rpython installation part and let the make rules pull in PyPy's source tree itself it should work?

**Comment by heyLu** [comment]
Yes, that should work.

**Comment by prologic** [comment]
Thanks. I'll close this issue and report back when successfully built :)

**Comment by jmglov** [comment]
@prologic Hey man, is this working for you now?

**Comment by prologic** [comment]
@jmglov In fact it's compiled beautifully after a ``git pull`` (*there was an issue with some entrypoint thing*).

Steps for building on OS X;

```#!bash
brew install libuv boost
make build_with_jit
```

Done!

**Comment by prologic** [comment]
Probably need to ``brew install libffi`` as well.

**Comment by thomasmulvaney** [comment]
Glad you've got it working. Closing this.

**Comment by prologic** [comment]
Do we want to add instructions on how to build this on OS X? There are no official docs per se yet right? How about adding it to the README?

**Comment by thomasmulvaney** [comment]
Sounds like a good idea. There is also a section on installation in the wiki https://github.com/pixie-lang/pixie/wiki/Installation which doesn't cover OS X

**Comment by prologic** [comment]
Updated to include OS X instructions.

**Comment by heyLu** [comment]
Thanks!

**Comment by prologic** [comment]
No problem!

On Wednesday, December 9, 2015, Lucas Stadler <notifications@github.com>
wrote:

> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixie-lang/pixie/issues/457#issuecomment-163385771>.
>


-- 

James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
